const podcasts = {
  
  card19: {
    id: 19,
    image: 'https://i.ytimg.com/vi/6BhAWF_jncc/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCPsSATNoxkU9cD9M1ZbY2S5UT2Nw',
    title: 'Kakolu - Miwa Cast #19',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy',
    youtube: 'https://www.youtube.com/watch?v=6BhAWF_jncc',
    spotify: 'https://open.spotify.com/show/4i7myM2dBJMz60uVXLlPGg',
  },

  card18: {
    id: 18,
    image: 'https://i.ytimg.com/vi/qp8lXqTbRrc/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBBIpvC0jCk5Al7KRp66ULmcxj3VQ',
    title: 'Daniel Cortez - Miwa Cast #18',
    description: 'Se você gosta de verdades esse episódio é feito para você, DANIEL CORTEZ conta tudo sobre sua experiência como MANAGER E TEAM MANAGER e também fala sobre sua passagem na VOLCOM e o trabalho feito com YAGO DORA e diversos atletas premiados no mundo do surf!',
    youtube: 'https://www.youtube.com/watch?v=qp8lXqTbRrc',
    spotify: 'https://open.spotify.com/episode/72Bb8ySxbt63xXrZIGSXlM',
  },

  card17: {
    id: 17,
    image: 'https://i.ytimg.com/vi/3h4pizbNwDI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBpZ790v5-Yw8YDP7_85FeJ3CWxiA',
    title: 'Noa Danucalov e George Alves - Miwa Cast #17',
    description: 'Nossos ATLETAS estão na área para contar um pouco da experiência e também de como é enfrentar os amigos dentro da agua!',
    youtube: 'https://www.youtube.com/watch?v=3h4pizbNwDI',
    spotify: 'https://open.spotify.com/episode/4EiE3Io6EGJXYOgXbo6Be0',
  },

  card16: {
    id: 16,
    image: 'https://i.ytimg.com/vi/SARyaLiXL-M/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCOgVErfN01dCfqWk31T3tv1MN2ew',
    title: 'Erico Bomfim - Miwa Cast #16',
    description: 'MIWACAST também é arte meu amigo!! Erico Bomfim vem pra contar um pouco mais sobre suas obras que estão espalhadas por toda a cidade de Santos e também algumas histórias que marcaram essa carreira no mundo da ARTE!!!',
    youtube: 'https://www.youtube.com/watch?v=SARyaLiXL-M',
    spotify: 'https://open.spotify.com/episode/76ViOf8WM1FdlC9Sj1PU4Y',
  },

  card15: {
    id: 15,
    image: 'https://i.ytimg.com/vi/lp9JsMRMiEg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBiXI0OjfOF5eLhbg60cszYflAffw',
    title: 'Vini Palma - Miwa Cast #15',
    description: 'O FUTURO DO BRAZILIAN STORM está no nosso PODCAST. VINI PALMA vem pra contar sobre seus títulos que apesar da pouca idade, ja vem acumulando vários troféus e também bater um papo sobre seu futuro muito promissor!',
    youtube: 'https://www.youtube.com/watch?v=lp9JsMRMiEg&t=1390s',
    spotify: 'https://open.spotify.com/episode/0kVwrfKFhzFa9fqqEXaSW6',
  },
  card14: {
    id: 14,
    image: 'https://i.ytimg.com/vi/ucNewLtN1hI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCyLrvaAoIK-_UfCj9XH38LeCOpZA',
    title: 'Mauro Rabelle e Paulo Issa - Miwa Cast #14',
    description: 'Nesse episodio você vai descobrir como funciona um campeonato de surf, desde as NARRAÇÕES COM O GRANDE PAULO ISSA até o sistema de notas com o nosso juiz MAURO RABELLE que conta tudo como funciona uma bancada na hora das grandes competições.',
    youtube: 'https://www.youtube.com/watch?v=ucNewLtN1hI',
    spotify: 'https://open.spotify.com/episode/6KZijF5Vfge8I8jTtKfMdE',
  },
  card13: {
    id: 13,
    image: 'https://i.ytimg.com/vi/OJl83aOSVX8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCAf4VjePZcZ0FZ2tjOUz9TctLNHA',
    title: 'Tiago Bulhões - Miwa Cast #13',
    description: 'Você está preparado para uma aula de surf e equipamentos? Tiago Bulhões está em nossa casa passando um pouco dos seus anos de experiências e seus conhecimento sobre tudo o que é ligado ao Surf. Venha conferir!!!',
    youtube: 'https://www.youtube.com/watch?v=OJl83aOSVX8',
    spotify: '',
  },
  card12: {
    id: 12,
    image: 'https://i.ytimg.com/vi/iNcg4qMp0Cg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC3hzfuuOABkgeaQ2Jkn6Fql9BJBA',
    title: 'Fafa Menezes e Vanessa Naufel - Miwa Cast #12',
    description: `Hora de falar um pouco de moda e empreendedorismo nesse Podcast. Fafa Menezes e Vanessa Naufel estão dando um show na Baixada Santista`,
    youtube: 'https://www.youtube.com/watch?v=iNcg4qMp0Cg&t=3112s',
    spotify: 'https://open.spotify.com/episode/2T7jNZMV9bxYlcieeuUk8y',
  },
  card11: {
    id: 11,
    image: 'https://i.ytimg.com/vi/HMeGtkSn-NM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBPtg2h-FXhq_MD81ElRohRgZetGw',
    title: 'Palhaço Saracura - Miwa Cast #11',
    description: 'ISSO MESMO, o Palhaço surfista Saracura esta em nossa casa para contar um pouco mais sobre sua vida e também sobre como é ser o primeiro palhaço surfista.',
    youtube: 'https://www.youtube.com/watch?v=HMeGtkSn-NM',
    spotify: 'https://open.spotify.com/episode/040SC8c28nkgRuxVXhgUaw',
  },
  card10: {
    id: 10,
    image: 'https://i.ytimg.com/vi/oN6cw0SrLOE/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBxXsQR61v4Mn4tBPhn9yTet2sCZg',
    title: 'Bianca Azevedo e Gabriella Andrade - MiwaCast #10',
    description: 'E esse papo resenha que tivemos com essas duas revelações do longboard, é a familia do Posto 2 na área!',
    youtube: 'https://www.youtube.com/watch?v=oN6cw0SrLOE&t=1442s',
    spotify: 'https://open.spotify.com/episode/1NBS73ozv5gH5XcU4sxcDQ',
  },
  card9: {
    id: 9,
    image: 'https://i.ytimg.com/vi/IkXWeOsJYHo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDCXTI2f_0U3haTSzZbZyKJDXRAdQ',
    title: 'Jojó de Olivença - MiwaCast #09',
    description: 'O cara que nunca perdeu para o Kelly Slater esta em nossa casa, venha conferir o que a lenda Jojó de Olivença tem para nos contar!',
    youtube: 'https://www.youtube.com/watch?v=IkXWeOsJYHo&t=1973s',
    spotify: 'https://open.spotify.com/episode/6mLckmEKqKjwDiaNSoDzwT',
  },
  card8: {
    id: 8,
    image: 'https://i.ytimg.com/vi/efX-TpC8n_A/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD4s-M7Q-kfF5UZJ_TyY7WsyBtI9Q',
    title: 'Marcelo e Neco Carbone - MiwaCast #08',
    description: 'Família Carbone na área pra contar como foi a trajetória para se tornar um dos shapers mais tradicionais da Baixada e o ensinamento que foi passado de pai para filho.',
    youtube: 'https://www.youtube.com/watch?v=efX-TpC8n_A',
    spotify: 'https://open.spotify.com/episode/5GDDp6s2wTrARvmoQHxyrK',
  },
  card7: {
    id: 7,
    image: 'https://i.ytimg.com/vi/-7o4PsSzlcA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDf3pXz57XNXiIVHFhVycqaoHZrAQ',
    title: 'LEANDRO "MIWA" e MARCELO "SAL NA VEIA" - MiwaCast #07',
    description: 'Esse elenco de peso hoje com Leandro Navarro, proprietário da Miwa Beach Club e Marcelo que é proprietário da loja Sal na Veia, nesse papo é quebrado alguns mitos sobre a rivalidade entre as lojas de surfwear na baixada santista e sobre projetos futuros para ajudar toda a cena do surf.  ',
    youtube: 'https://www.youtube.com/watch?v=-7o4PsSzlcA',
    spotify: 'https://open.spotify.com/episode/0rFy6hVRE9yxzHOhE255hJ',
  },
  card6: {
    id: 6,
    image: 'https://i.ytimg.com/vi/FXcJNvnFzKg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD7qm6gWmIEkdpNWIaKm_80FHDOuQ',
    title: 'WESLLEY DANTAS - MiwaCast #06',
    description: 'Diretamente de Ubatuba para a nossa casa, essa fera do QS vem contar como foi sua trajetória para chegar ao ponto que está atualmente e também revela seus próximos passos e seus objetivo para o próximo ano. Venha Conferir!',
    youtube: 'https://www.youtube.com/watch?v=FXcJNvnFzKg',
    spotify: 'https://open.spotify.com/episode/5ncSp0raoNfCY0s9sgjaoM',
  },
  card5: {
    id: 5,
    image: 'https://i.ytimg.com/vi/Pdj-U8Rug8Q/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLABSvbaAo1lW6F4AkLoztaZRLHG0Q',
    title: 'CAROL BASTIDES - MiwaCast #05',
    description: 'E essa revelação apareceu na Miwa Beach Club, Carol Bastides conta como foi o começo no surf e todas as suas aventuras pelo Brasil e também conta como foi o inicio de sua parceria com  IF15 de Italo Ferreira e seus encontros em Baía Formosa.',
    youtube: 'https://www.youtube.com/watch?v=Pdj-U8Rug8Q',
    spotify: 'https://open.spotify.com/episode/1wCTkgIT3FPMLUYZBo425Z',
  },
  card4: {
    id: 4,
    image: 'https://i.ytimg.com/vi/R1EYtxQS7TU/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD-MUnRsDWGI5Rd-cRPQYPpDvuzVA',
    title: 'SYLVIO "TICO" E ADRIANO "TECO" (SILVER SURF) - MiwaCast #04',
    description: 'A Silver Surf está de volta na nossa loja, mas agora com Sylvio "Tico" e com o recordista em participação Adriano "Teco", contando mais sobre a historia da Silver Surf e a ascensão de ITALO FERREIRA nas Olimpíadas e a possível chance de mais um título. ',
    youtube: 'https://www.youtube.com/watch?v=R1EYtxQS7TU&t=437s',
    spotify: 'https://open.spotify.com/episode/0ACl0YsEex7ggDJEXqPbSM',
  },
  card3: {
    id: 3,
    image: 'https://i.ytimg.com/vi/727f91C1Jcw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAXlZv0XuHTLCkIUbjNTxrfs82TaA',
    title: 'JOÃO VITOR E MARIA CLARA - MiwaCast #03',
    description: 'Dose dupla de talento dentro da nossa loja, nesse episodio de hoje temos a maravilhosa família de João Vitor e Maria Clara.',
    youtube: 'https://www.youtube.com/watch?v=727f91C1Jcw&t=1s',
    spotify: 'https://open.spotify.com/episode/2gHbik6ScnVapdBYZReyAE',
  },
  card2: {
    id: 2,
    image: 'https://i.ytimg.com/vi/5_v6z9WJnjE/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCwWZViyb2MjoBM55ua7Ih22TC5Fg',
    title: 'JAIR DE OLIVEIRA E JACUÍ - MiwaCast #02',
    description: 'No episódio de hoje temos a ilustre presença do multicampeão Jair de Oliveira que conta suas incríveis experiências que passou durante sua carreira profissional e a presença do Legend de Santos-SP Jacuí, conversando um pouco sobre os antigos tempos de competição e as histórias do mundo do surf.',
    youtube: 'https://www.youtube.com/watch?v=5_v6z9WJnjE',
    spotify: 'https://open.spotify.com/episode/7KPnm0D5c6SHDIEUJFSa8l',
  },
  card1: {
    id: 1,
    image: 'https://i.ytimg.com/vi/Fl0fek-CCDw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBp5zdlPZOI5Xm7CNWUd1O9XJRRrw',
    title: 'EDINHO LEITE E WALTER THEODOSIO - MiwaCast #01',
    description: 'Nesse podcast contamos com a presença de Edinho Leite que é comentarista da ESPN e do "Serie ao Fundo" e Walter Theodosio um Legend do longboard em Santos-SP, falando um pouco do surf local e das novidades do mundo do surf',
    youtube: 'https://www.youtube.com/watch?v=Fl0fek-CCDw',
    spotify: 'https://open.spotify.com/episode/3HfX5N4VUN4Vz65smdtULx',
  },
  card00: {
    id: 0,
    image: 'https://i.ytimg.com/vi/rhQUMDIJwqc/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCvba04ED2Yityvey6swpO-tbXrsQ',
    title: 'RICARDO "PIRO" E TECO (SILVER SURF BOARDS) - MiwaCast #00',
    description: 'Um bate-papo com Ricardo "Piro" e Teco falando sobre a SILVER SURF BOARDS e também o sobre a parceria com ITALO FERREIRA!',
    youtube: 'https://www.youtube.com/watch?v=rhQUMDIJwqc&t=4740s',
    spotify: 'https://open.spotify.com/episode/5CM4vUbg3dqIoNX4gKXNgs',
  },
}

export default podcasts;
